input_number:
  bathroom_set_hott_water:
    name: Bathroom_set_hot_water
    unit_of_measurement: "m³"
    mode: box
    min: 0
    max: 1000000
    step: 0.001
    icon: mdi:water-plus
  bathroom_set_cold_water:
    name: Bathroom_set_cold_water
    unit_of_measurement: "m³"
    mode: box
    min: 0
    max: 1000000
    step: 0.001
    icon: mdi:water-minus

input_button:
  sync_bathroom_totals:
    name: sync_bathroom_totals
    icon: mdi:water-sync

input_text:
  bathroom_hot_water_state:
    name: bathroom_hot_water_state
    initial: "unnown"

automation:
  - id: "bathroom_set_hot_water"
    alias: bathroom_set_hot_water
    description: ""
    mode: single
    variables:
      hot_water_total: "{{ states('input_number.bathroom_set_hot_water') | float }}"
      cold_water_total: "{{ states('input_number.bathroom_set_cold_water') | float }}"
    triggers:
      - trigger: state
        entity_id:
          - input_button.sync_bathroom_totals
    action:
      - action: esphome.bathroom_warp_set_hot_water_total
        data:
          value: "{{ hot_water_total }}"
      - action: esphome.bathroom_warp_set_cold_water_total
        data:
          value: "{{ cold_water_total }}"
      - action: telegram_bot.send_message
        data:
          message: >
            Синхронизация счетчиков воды в ванной:
            горячая: {{ hot_water_total }}m³
            холодная: {{ cold_water_total }}m³

  - id: bathroom_hot_water_state_message
    alias: bathroom_hot_water_state_message
    description: ""
    variables:
      upper_treshold: 50
      lower_treshold: 40
      temperature: "{{ states('sensor.bathroom_warp_hot_water_temperature') | float }}"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - sensor.bathroom_warp_hot_water_temperature
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ temperature > upper_treshold }}
              - condition: template
                value_template: >
                  {{ states('input_text.bathroom_hot_water_state') != "normal" }}
            sequence:
              - action: input_text.set_value
                target:
                  entity_id: input_text.bathroom_hot_water_state
                data:
                  value: "normal"
              - action: telegram_bot.send_message
                data:
                  message: >
                    Температура воды в ванной в норме: {{ temperature }}°C
          - conditions:
              - condition: template
                value_template: >
                  {{ temperature < lower_treshold }}
              - condition: template
                value_template: >
                  {{ states('input_text.bathroom_hot_water_state') != "cold" }}
            sequence:
              - action: input_text.set_value
                target:
                  entity_id: input_text.bathroom_hot_water_state
                data:
                  value: "cold"
              - action: telegram_bot.send_message
                data:
                  message: >
                    Температура воды в ванной меньше {{ lower_treshold }}°C
