input_text:
  toilet_hot_water_state:
    name: toilet_hot_water_state
    initial: "unknown"

automation:
  - id: "sync_toilet_totals"
    alias: sync_toilet_totals
    description: ""
    mode: single
    variables:
      hot_water_total: "{{ states('input_number.toilet_set_hot_water') | float }}"
      cold_water_total: "{{ states('input_number.toilet_set_cold_water') | float }}"
    triggers:
      - trigger: state
        entity_id:
          - button.toilet_warp_sync_totals
    action:
      - action: esphome.toilet_warp_set_hot_water_total
        data:
          value: "{{ hot_water_total }}"
      - action: esphome.toilet_warp_set_cold_water_total
        data:
          value: "{{ cold_water_total }}"
      - action: telegram_bot.send_message
        data:
          message: >
            Синхронизация счетчиков воды в туалете:
            горячая: {{ hot_water_total }}m³
            холодная: {{ cold_water_total }}m³

  - id: toilet_hot_water_state_message
    alias: toilet_hot_water_state_message
    description: ""
    variables:
      upper_treshold: 50
      lower_treshold: 40
      temperature: "{{ states('sensor.toilet_warp_hot_water_temperature') | float }}"
    mode: single
    triggers:
      - trigger: state
        entity_id:
          - sensor.toilet_warp_hot_water_temperature
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: >
                  {{ temperature > upper_treshold }}
              - condition: template
                value_template: >
                  {{ states('input_text.toilet_hot_water_state') != "normal" }}
            sequence:
              - action: input_text.set_value
                target:
                  entity_id: input_text.toilet_hot_water_state
                data:
                  value: "normal"
              - action: telegram_bot.send_message
                data:
                  message: >
                    Температура воды в туалете в норме: {{ temperature }}°C
          - conditions:
              - condition: template
                value_template: >
                  {{ temperature < lower_treshold }}
              - condition: template
                value_template: >
                  {{ states('input_text.toilet_hot_water_state') != "cold" }}
            sequence:
              - action: input_text.set_value
                target:
                  entity_id: input_text.toilet_hot_water_state
                data:
                  value: "cold"
              - action: telegram_bot.send_message
                data:
                  message: >
                    Температура воды в туалете меньше {{ lower_treshold }}°C
