input_number:
  bathroom_set_hott_water:
    name: Bathroom_set_hot_water
    unit_of_measurement: "m3"
    mode: box
    initial: 100
    min: 0
    max: 1000000
    step: 0.001
    icon: mdi:water
  bathroom_set_cold_water:
    name: Bathroom_set_cold_water
    unit_of_measurement: "m3"
    mode: box
    initial: 100
    min: 0
    max: 1000000
    step: 0.001
    icon: mdi:water
  # bathroom_hot_water_temperature_min:
  #   name: Bathroom_hot_water_Tmin
  #   unit_of_measurement: "℃"
  #   mode: box
  #   initial: 40
  #   min: 20
  #   max: 95
  #   step: 0.1
  #   icon: mdi:ThermometerChevronDown

automation:
  - id: "bathroom_set_hot_water"
    alias: bathroom_set_hot_water
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - input_number.bathroom_set_hot_water
    conditions: []
    action:
      - service: esphome.water_bathroom_set_total_hot_water_consumption
        data:
          value: "{{ states('input_number.bathroom_set_hot_water') | float }}"
    mode: single
  - id: "bathroom_set_cold_water"
    alias: bathroom_set_cold_water
    description: ""
    triggers:
      - trigger: state
        entity_id:
          - input_number.bathroom_set_cold_water
    conditions: []
    action:
      - service: esphome.water_bathroom_set_total_cold_water_consumption
        data:
          value: "{{ states('input_number.bathroom_set_cold_water') | float }}"
    mode: single
  - id: "bathroom_hot_water_temperature_low"
    alias: "bathroom_hot_water_temperature_low"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.water_bathroom_hot_water_temperature
        below: 45.0
      # for:
      #   minutes: 5
    conditions: []
    action:
      - service: telegram_bot.send_message
        data:
          message: "Температура горячей воды в ванной меньше {{ trigger.below }}℃"
  - id: "bathroom_hot_water_temperature_good"
    alias: "bathroom_hot_water_temperature_good"
    description: ""
    triggers:
      - trigger: numeric_state
        entity_id:
          - sensor.water_bathroom_hot_water_temperature
        above: 50
    conditions: []
    action:
      - service: telegram_bot.send_message
        data:
          message: "Температура горячей воды в ванной в норме"
