# light:
#   - platform: template
#     lights:
#       hallway_light:
#         friendly_name: "Hallway light"
#         turn_on:
#           service: mqtt.publish
#           data:
#             topic: ir_room/cmnd/IRsend
#             payload: '{"Protocol":"NEC","Bits":32,"Data":"0x05ED9768"}'
#         turn_off:
#           service: mqtt.publish
#           data:
#             topic: ir_room/cmnd/IRsend
#             payload: '{"Protocol":"NEC","Bits":32,"Data":"0x05ED9768"}'
automation:
  - id: "Door_to_open"
    alias: "Door is open"
    description: ""
    triggers:
      - trigger: state
        entity_id: binary_sensor.0x00158d0002890189_contact
        to: "on"
    condition: []
    action:
      - service: notify.telegram_main
        data:
          message: "Дверь🚪"
  - id: "Analog_indicator"
    alias: "Analog_indicator"
    variables:
      temperature: "{{ states('sensor.water_bathroom_hot_water_temperature') | float }}"
    description: ""
    triggers:
      - trigger: state
        entity_id: sensor.water_bathroom_hot_water_temperature
    action:
      - service: number.set_value
        data_template:
          entity_id: number.analog_indicator_level
          value: "{{ temperature }}"
